"""Compile the supplied design reference into one versioned, local stylesheet.

No React bundle or sample data is executed. Original reference stays separate.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "design/reference"
TARGET = ROOT / "zhidao_v4/static/app/design-system.css"
FILES = ["tokens/typography.css", "tokens/palette.css", "tokens/semantic.css",
         "tokens/spacing.css", "tokens/material.css", "tokens/luna.css",
         "tokens/night.css", "skins/aqua.css", "skins/luna.css",
         "skins/games.css", "skins/sections.css", "skins/staff.css"]

# Structural aliases only: preserve all live IDs, event handlers and markup.
ALIASES = {
    "zd-header": "app-header", "zd-brand": "app-brand",
    "zd-profile-fab": "profile-fab", "zd-dock": "app-dock",
    "zd-titlebar": "case-titlebar", "zd-statusbar": "terminal-footer",
    "zd-window": "case-window", "zd-cn": "nav-cn",
}

def compile_css():
    parts = ["/* Generated by tools/build_design_system.py; edit reference or design-system-bridge.css. */"]
    for name in FILES:
        text = (SOURCE / name).read_text(encoding="utf-8")
        text = text.replace('../../assets/', './assets/').replace('../assets/', './assets/')
        for reference, live in ALIASES.items():
            text = re.sub(r'\.' + re.escape(reference) + r'(?![\w-])',
                          f':is(.{reference},.{live})', text)
        parts.append(f"/* Source: {name} */\n{text}")
    return "\n".join(parts)

def build():
    TARGET.write_text(compile_css(), encoding="utf-8")

if __name__ == "__main__":
    build()
